version: '3'

services:
  python-local:
    build:
      context: .
      dockerfile: "Dockerfile"
    user: root
    container_name: python-local
    image: python:3.9.0a6-buster
    ports:
      - 8888:8888
    volumes:
            - ./:/work
    
